### ISSUE TITLE
ArtificeResourcePack.getName causes a NPE when initializing virtual resource packs

### ISSUE THREAD

**Issue by Shnupbups** [artificemc/artifice#5]
Using Artifice in a dev environment, I get an NPE crash when attempting to start Minecraft.

The crash: https://paste.ee/p/mrsBa
The only code I currently have which uses Artifice: https://paste.ee/p/V9VzC

**Comment by swordglowsblue** [comment]
For now, you should be able to fix it by adding `pack.setDisplayName(name)` to your pack definition. I'll look into the underlying issue more when I have time later.

**Comment by Shnupbups** [comment]
Cheers, thanks for the temporary fix!

**Comment by swordglowsblue** [comment]
That commit should fix the issue, not a great solution but it works. You can use the `0.3.2-dev-SNAPSHOT` build from Jitpack if you want, or it should be out sometime in the next few days depending how much time I have to work on it (I want to get the entire API javadoc'd first).
