### ISSUE TITLE
Reloading resources when on a multiplayer server breaks Artifice resource packs

### ISSUE THREAD

**Issue by Shnupbups** [artificemc/artifice#9]
Reloading Minecraft's resources (either through enabling/disabling a resource pack in the menu, or using F3+T) breaks Artifice resource packs.

I was playing AoF Strawberry, which has Extra Pieces (which JiJ's Artifice 0.3.4) and had some decoration placed down with blocks that use models generated with Artifice. I reloaded resources, and they became the pink and black cubes of missing model-ness.

[Image](https://media.discordapp.net/attachments/582044241530847253/611134244462395393/2019-08-14_06.48.19.png?width=1423&height=754) (not mine, but showcases the same thing under the same circumstances)

**Comment by swordglowsblue** [comment]
Can you reproduce the issue with just Extra Pieces / Artifice? If not, what other mods are necessary to cause the issue? I tested reloading extensively, so it seems weird that it wouldn't work properly.

**Comment by Shnupbups** [comment]
Just tested, this does not happen in Singleplayer, only on a Multiplayer server. Weird.

**Comment by swordglowsblue** [comment]
Are there any errors in the console when this happens, and can it be reproduced with only Artifice and the mod depending on it?

**Comment by Shnupbups** [comment]
Yes, this does occur on a server with just Fabric API and Extra Pieces (and thus Artifice). Both the client and server had only these mods, and what was this:
![2019-08-22_00 45 24](https://user-images.githubusercontent.com/2484721/63442600-ba29d700-c476-11e9-8cd4-8c0825c3697a.png)
became this after F3+T
![2019-08-22_00 46 42](https://user-images.githubusercontent.com/2484721/63442601-bac26d80-c476-11e9-9159-a331a043382a.png)

The log can be found here: https://gist.github.com/Shnupbups/693689b6becb7b1a618731b1be724e94
Warning though, it's basically just 35000 lines of Minecraft complaining json files don't exist.

**Comment by swordglowsblue** [comment]
I can't see anything in the Extra Pieces code that might cause it. I'm in school now so the amount of time I can spend working on Artifice is limited, but I'll take a look when I can and see if I can figure out why. The main issue I've had with testing it is my test mod is borked and acts up on servers in and of itself, which I in no way understand the cause of and I'll need to fix first to even be able to test this.

**Comment by swordglowsblue** [comment]
I think I've found the reason my test mod was acting up, so I'll take a look when I have the chance and see if I can fix this. Worst case scenario I'll have it fixed in 0.4.0, hopefully I can get a patch out as a 0.3.5.

**Comment by swordglowsblue** [comment]
I'm able to reproduce this, but I've got no idea why it happens yet. Will update when I know more.

**Comment by swordglowsblue** [comment]
Fixed by 9c220af, 0.3.5 releasing soon.

**Comment by swordglowsblue** [comment]
Note to self: Don't register client-side only registries with `Registry.REGISTRIES`, or it will be picked up by Fabric's registry sync and break on servers.
